--
swagger: '2.0'
info:
  version: 0.0.1
  title: First Swagger API
  schemes:
    - "http"
  consumes:
    - "application/json"
  produces:
    - "application/json"
paths:
  /test:
    get:
      responses:
        200:
          description: "A response"
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:${stageVariables.Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${stageVariables.Region}:${stageVariables.AccountId}:function:${stageVariables.ServerlessExpressLambdaFunctionName}/invocations
        credentials: null
        httpMethod: POST
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: "{\"statusCode\": 200}"
            type: mock
x-amazon-apigateway-binary-media-types:
  - '*/*'
definitions:
  Empty:
    type: object
    title: Empty Schema